security:
    ignore-cvss-severity-below: 0
    ignore-cvss-unknown-severity: False
    ignore-vulnerabilities:
        70612:
            reason: https://github.com/pallets/jinja/issues/1994#issuecomment-2146978470
    continue-on-vulnerability-error: False
