[app]
healthcare_adapter=mock
addressing_adapter=mock
loglevel=debug
mock_base_url=http://mock:8002

[database]
dsn=sqlite:///:memory:

[zorgab]
base_url=https://zab.test.aorta-zorg.nl/zab-ro
mtls_cert_file=
mtls_key_file=
mtls_chain_file=
proxy=

[uvicorn]
host=0.0.0.0
port=8006
reload=True
use_ssl=False
ssl_base_dir=
ssl_cert_file=
ssl_key_file=

[jwe]
signing_private_key_path=/src/secrets/private_signing.key
encryption_public_key_path=/src/secrets/placeholder_jwe_encryption.pub

[healthcarefinder]
; When set to True, a predefined search query can force the use of a ZorgAB mock adapter
allow_search_bypass=True
