name: "Python src packager"
description: "Exports a Python src package"
inputs:
  package_file_name:
    description: "Name of the package"
    required: true

runs:
    using: "composite"
    steps:
        - name: Set release version
          shell: bash
          run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

        - name: Set package file name
          shell: bash
          run: echo "PACKAGE_FILE_NAME=${{ inputs.package_file_name }}_${{ env.RELEASE_VERSION }}" >> $GITHUB_ENV

        - name: Checkout code
          uses: actions/checkout@v4

        - name: Add version file
          shell: bash
          run: 'echo "{ \"version\": \"${{ env.RELEASE_VERSION }}\", \"git_ref\": \"$GITHUB_SHA\"}" > version.json'

        - name: Create tar
          shell: bash
          run: tar -czf ${{ env.PACKAGE_FILE_NAME }}.tar.gz app docs sql static tools version.json HOSTING_CHANGELOG.md app.conf.example

        - name: Upload release tar
          uses: actions/upload-artifact@v4
          with:
            name: ${{ env.PACKAGE_FILE_NAME }}
            path: ${{ env.PACKAGE_FILE_NAME }}.tar.gz
