name: "Setup app"
description: "Installs Python and packages for an application in a given directory using uv."
inputs:
    app-dir:
        description: Path to Python application
        default: "."
runs:
    using: "composite"

    steps:
        - name: Setup Python environment with uv
          uses: astral-sh/setup-uv@v7
          with:
             enable-cache: true
             python-version: "3.11"

        - name: Install dependencies
          shell: bash
          working-directory: ${{ inputs.app-dir }}
          run: uv sync --locked
