name: "Validate PR Description"
description: "Validates that the pull request description follows the pull request template."

runs:
  using: "composite"
  steps:
    - name: Init action
      shell: bash
      run: |
        set -euo pipefail

        BRANCH="${{ github.head_ref }}"

        echo "DEFAULT_TEMPLATE_PATH=.github/pull_request_template.md" >> "$GITHUB_ENV"

        if [[ "$BRANCH" == release/* ]]; then
          echo "TEMPLATE_PATH=.github/PULL_REQUEST_TEMPLATE/release_template.md" >> "$GITHUB_ENV"
        else
          echo "TEMPLATE_PATH=.github/PULL_REQUEST_TEMPLATE/change_template.md" >> "$GITHUB_ENV"
        fi

    - name: Fetch branch-specific PR template
      shell: bash
      run: |
        echo "Fetching branch-specific PR template from $TEMPLATE_PATH"
        if [ ! -f "$TEMPLATE_PATH" ]; then
          echo "ERROR: Branch-specific template not found at $TEMPLATE_PATH"
          exit 1
        fi
        cp "$TEMPLATE_PATH" pr_template.txt

    - name: Fetch default PR template
      shell: bash
      run: |
        echo "Fetching default PR template from path $DEFAULT_TEMPLATE_PATH"
        if [ ! -f "$DEFAULT_TEMPLATE_PATH" ]; then
          echo "WARNING: Default PR template not found at $DEFAULT_TEMPLATE_PATH, skipping comparison."
          touch default_pr_template.txt
        else
          cp "$DEFAULT_TEMPLATE_PATH" default_pr_template.txt
        fi

    - name: Check if PR has a description
      shell: bash
      run: |
        PR_BODY=$(jq --raw-output ".pull_request.body // empty" "$GITHUB_EVENT_PATH")
        if [ -z "$PR_BODY" ]; then
          echo "ERROR: PR description is missing."
          exit 1
        fi
        echo "$PR_BODY" > pr_body.txt

    - name: Compare PR body to templates
      shell: bash
      run: |
        function normalize_and_compare() {
          local body_file="$1"
          local template_file="$2"
          local label="$3"
          sed '/^\s*$/d' "$body_file" | sed 's/[[:space:]]//g' > body_clean.txt
          sed '/^\s*$/d' "$template_file" | sed 's/[[:space:]]//g' > template_clean.txt
          if cmp -s body_clean.txt template_clean.txt; then
            echo "ERROR: PR description matches the $label template too closely. Please provide a meaningful description."
            exit 1
          else
            echo "PR description differs sufficiently from the $label template."
          fi
        }
        normalize_and_compare pr_body.txt default_pr_template.txt "default"
        normalize_and_compare pr_body.txt pr_template.txt "branch-specific"

    - name: Ensure all checkboxes are checked
      uses: mheap/require-checklist-action@v2
