name: CI

on:
    workflow_dispatch:
    pull_request:
    push:
        branches:
            - develop
            - main

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    lint:
        name: Run code linter
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v6

            - name: Install dependencies
              uses: ./.github/actions/setup-app

            - name: Lint
              run: uv run $(make lint --just-print --silent)

    format:
        name: Run formatter
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v6

            - name: Install dependencies
              uses: ./.github/actions/setup-app

            - name: Find format differences
              run: uv run $(make format-diff --just-print --silent)

    type-check:
        name: Check static types
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v6

            - name: Install dependencies
              uses: ./.github/actions/setup-app

            - name: Check static types
              run: uv run $(make type-check --just-print --silent)

    spelling-check:
        name: Run spelling check
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v6

            - name: Install dependencies
              uses: ./.github/actions/setup-app

            - name: Run spelling check
              run: uv run $(make spelling-check --just-print --silent)

    test:
        name: Run the tests
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v6

            - name: Install dependencies
              uses: ./.github/actions/setup-app

            - name: Run the tests
              env:
                  CI_ENV: 1
              run: uv run $(make test --just-print --silent)

            - name: Upload coverage report
              uses: actions/upload-artifact@v7
              with:
                  name: coverage
                  path: coverage.xml

    sonar:
        name: SonarCloud
        runs-on: ubuntu-latest
        needs: test
        steps:
            - name: Checkout repository
              uses: actions/checkout@v6
              with:
                  fetch-depth: 0
            - name: Download coverage report
              uses: actions/download-artifact@v8

            - name: Run SonarQube scan
              uses: minvws/action-sonarqube@v1
              with:
                  sonar-token: ${{ secrets.SONAR_TOKEN }}
                  allow-run-on-dependabot: 'true'
