name: Create release packages

on:
  push:
    tags:
      - v*

env:
  PACKAGE_FILE_NAME: "mgo-location-addressing-api"
  PYTHON_VERSION: "3.11"

jobs:
  venv-package:
    runs-on: ubuntu-22.04
    steps:
      - name: Build venv package
        uses: minvws/nl-irealisatie-generic-pipelines/.github/actions/python-venv-package@1279864d6bfc79a6ac2666846cdb00c08ab6593f
        with:
          python_version: ${{ env.PYTHON_VERSION }}
          package_file_name: ${{ env.PACKAGE_FILE_NAME }}

  src-package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build source package
        uses: ./.github/actions/src-package
        with:
          package_file_name: ${{ env.PACKAGE_FILE_NAME }}
